env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "fX9ebEEr+JOuVtyvVGBuhkSFIL7jnhIRRJzd+EFJMSM+PchmesP4Pj/Sag7AH96ZfAxXJmm7Qr+ZrIKyIzsnRVzLQVZ8Vs3pK7+jEkHFj/n2q8QRia9bfBJgzMTuTeETpTI2qwN3HwkGKBDeByxJ21mfGlYLQPMqBkz4k0fnVW0="


dist: trusty
sudo: required

language: cpp

before_install:
  - sudo ls -l /etc/ssl/certs/
  - >
    echo -n | openssl s_client -connect scan.coverity.com:443 |
    sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' |
    sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - sudo apt-get install libxml2-dev libpng12-dev zlib1g-dev libcunit1-dev doxygen
  - sudo iptables -F
  - mkdir m4
  #- autoconf --version
  - autoreconf -fi
  #- fgrep RPCGEN_OPTS protocol/Makefile.in
  #- g++ -dumpversion
  - ./configure --disable-root-actions --with-noaaport --with-multicast
  #- fgrep MULTICAST config.status
  #- fgrep RPCGEN_OPTS protocol/Makefile

addons:
  coverity_scan:
    project:
      name: "Unidata/LDM"
      description: "Event-driven data-distribution package"
    notification_email: emmerson@ucar.edu
    build_command_prepend: true
    build_command:  "make"
    branch_pattern: master

script: make distcheck

after_failure:
  - pwd
